"""
I-914 QC Checklist template data.

Structure: list of parts, each with optional subparts and questions.
Each question has: code, description, where_to_verify.
"""

I914_TEMPLATE = {
    "name": "QC Checklist – I-914 (T-1)",
    "description": "Quality Control checklist for I-914 Application for T Nonimmigrant Status",
    "parts": [
        {
            "code": "Part 1",
            "name": "I-914 Part 1",
            "questions": [
                {"code": "1", "description": "Is the correct A or B box checked for this case?", "where_to_verify": "BIO CALL / INTAKE / PREVIOUS DOCS"},
            ],
        },
        {
            "code": "Part 2",
            "name": "I-914 Part 2",
            "questions": [
                {"code": "1", "description": "Is the applicant's full legal name correct?", "where_to_verify": "Birth Certificate or Passport"},
                {"code": "2", "description": "Are any other names used by the applicant listed correctly?", "where_to_verify": "FBI RECORDs and/or the BIO CALL, Otros Documentos"},
                {"code": "3", "description": "Is the applicant's physical address correct?", "where_to_verify": "Bio Call, Google Maps and Proof of Address"},
                {"code": "4", "description": "Is the safe mailing address correct? Law Offices of Manuel E. Solis, PLLC P.O. Box 231704 Houston, TX 77223", "where_to_verify": "Is this address in the section the Houston office address"},
                {"code": "4.A", "description": "Accredited representative information: Is the additional box in the bottom right corner of the G-28 checked, and is Attorney Manuel E. Solis's bar number entered correctly? USCIS Online Account Number", "where_to_verify": "MUST BE: Attorney State License Bar Number 18826790. USCIS Online Account Number - 087361245002"},
                {"code": "5", "description": "Is the applicant's A-Number correct?", "where_to_verify": "Intake, BIO call or Previous Immigration Process Docs, FBI RAPSHEET"},
                {"code": "6", "description": "Is the applicant's USCIS Online Account Number correct?", "where_to_verify": "USCIS Online Account Number - 087361245002"},
                {"code": "7", "description": "Is the applicant's U.S. Social Security Number (SSN), if any, correct? *Just SSN Issued by the Government", "where_to_verify": "Bio Call / Copy of SS Card"},
                {"code": "8", "description": "Is the applicant's gender correct?", "where_to_verify": "Birth Certificate / Passport"},
                {"code": "9", "description": "Is the applicant's marital status correct?", "where_to_verify": "Intake/Bio Call / Marriage Cert"},
                {"code": "10", "description": "Is the applicant's date of birth correct? *Remember to use the proper format (Mmm DD YYYY)", "where_to_verify": "Birth Cert / Passport"},
                {"code": "11", "description": "Is the applicant's place of birth correct?", "where_to_verify": "Birth Cert"},
                {"code": "12", "description": "Is the applicant's country of citizenship or nationality correct?", "where_to_verify": "Birth Cert / Passport"},
                {"code": "13", "description": "Is the passport or travel document number, if any, correct?", "where_to_verify": "Passport / I94 / Visa / Other Doc"},
                {"code": "14", "description": "Is the country that issued the passport or travel document, if any, correct?", "where_to_verify": "Passport / I94 / Visa / Other Doc"},
                {"code": "15", "description": "Is the issue date for the passport or travel document, if any, correct?", "where_to_verify": "Passport / I-94 / Visa"},
                {"code": "16", "description": "Is the expiration date for the passport or travel document, if any, correct? *Remember to use the proper format (Mmm DD YYYY)", "where_to_verify": "Passport / I94 / Visa"},
                {"code": "17", "description": "Is the place of the applicant's last entry into the United States correct? *City or Town *State", "where_to_verify": "Intake/Bio Call / Declaration/FBI/FOIA"},
                {"code": "18", "description": "Is the date of the applicant's last entry into the United States correct? *Remember to use the proper format (Mmm DD YYYY)", "where_to_verify": "Intake/Bio Call / Declaration/FBI/FOIA"},
                {"code": "19", "description": "Is the Form I-94 Arrival-Departure Record Number, if any, correct?", "where_to_verify": "I94/FOIA"},
                {"code": "20", "description": "Is the applicant's current nonimmigrant status correct? *IF NO STATUS - No Legal Status*", "where_to_verify": "Intake/Bio Call/Immigration Doc"},
            ],
        },
        {
            "code": "Part 3",
            "name": "I-914 Part 3",
            "questions": [
                {"code": "3.1", "description": "Do the records show that the applicant has been a victim of a severe form of trafficking in persons?", "where_to_verify": "Intake; Bio Call; Declaration: must be checked (true/yes)"},
                {"code": "3.2.A", "description": "Do the records show that the applicant cooperated with reasonable requests for assistance from law enforcement?", "where_to_verify": "LEA Report email; cover letter; Declaration; police reports."},
                {"code": "3.2.B", "description": "Do the records show that the applicant is exempt from the cooperation requirement because of age or trauma?", "where_to_verify": "Intake; Bio Call; Declaration; Birth Certificate"},
                {"code": "3.3", "description": "Do the records show that the applicant is physically present in the United States, American Samoa, the Commonwealth of the Northern Mariana Islands, or at a port of entry on account of trafficking?", "where_to_verify": "Intake; Bio Call; must be checked yes, unless is a derivative outside the states."},
                {"code": "3.4", "description": "Do the records show that the applicant would suffer extreme hardship involving unusual and severe harm upon removal?", "where_to_verify": "Intake; Declaration part. \"Extreme Hardship if removal from the US\""},
                {"code": "3.5", "description": "Do the records show that the applicant reported the trafficking crime? Law Enforcement Agency and Office City or Town State ZIP Code Street Number and Name Apt. Flr. Number Ste. Daytime Telephone Number Case Number Circumstances", "where_to_verify": "LEA Report (HTPU (Human Trafficking Prosecution unit, US department of Justice); Police Report"},
                {"code": "3.6", "description": "Do the records show that the applicant was under 18 years of age when at least one act of trafficking occurred?", "where_to_verify": "Intake; Declaration; Birth certificate"},
                {"code": "3.7", "description": "Do the records show that the applicant complied with reasonable requests from Federal, State, Tribal, or local law enforcement authorities for assistance?", "where_to_verify": "LEA Report"},
                {"code": "3.8", "description": "Do the records show that this was the applicant's first time entering the United States? Date of Entry (Mmm DD YYYY) (2) Place of Entry City or Town and State Status", "where_to_verify": "Intake; Bio Call; Declaration; FBI; FOIA;"},
                {"code": "3.9", "description": "Do the records show that the applicant's most recent entry was on account of the trafficking claim?", "where_to_verify": "Intake; Declaration"},
                {"code": "3.10", "description": "Is the applicant requesting an Employment Authorization Document (EAD) when T nonimmigrant status is granted?", "where_to_verify": "Verify to answer YES Form I-765"},
                {"code": "3.11", "description": "Is the applicant now applying for one or more eligible family members?", "where_to_verify": "Contract, cover letter header regarding T-2, T-3, etc; form I-914 supplement A attached."},
            ],
        },
        {
            "code": "Part 4",
            "name": "I-914 Part 4 – Processing Information",
            "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
            "subparts": [
                {
                    "code": "4.1",
                    "name": "Criminal / Law Enforcement (including DHS/INS/military)",
                    "questions": [
                        {"code": "4.1.A", "description": "Do the records show that the applicant has committed a crime or offense for which they have not been arrested?", "where_to_verify": "Intake; Bio Call; Declaration/Affidavit; Criminal Record; FBI (most accurate, but some detentions only in statement)"},
                        {"code": "4.1.B", "description": "Do the records show that the applicant has been arrested, cited, or detained by any law enforcement officer (including DHS/INS/military) for any reason?", "where_to_verify": "Intake; Bio Call; Declaration; Criminal record; FBI; FOIA (as needed)"},
                        {"code": "4.1.C", "description": "Do the records show that the applicant has been charged with committing any crime or offense?", "where_to_verify": "Court disposition; Criminal record; FOIA, FBI"},
                        {"code": "4.1.D", "description": "Do the records show that the applicant has been convicted of a crime or offense (even if later expunged or pardoned)?", "where_to_verify": "Outcome; Court disposition; Criminal record; FBI"},
                        {"code": "4.1.E", "description": "Do the records show that the applicant has been placed in alternative sentencing / rehabilitative programs (diversion, deferred prosecution, withheld adjudication, deferred adjudication)?", "where_to_verify": "Outcome; Court disposition; Criminal record; FBI"},
                        {"code": "4.1.F", "description": "Do the records show that the applicant has received a suspended sentence, been placed on probation, or been paroled?", "where_to_verify": "Outcome; Court disposition; Criminal record; FBI"},
                        {"code": "4.1.G", "description": "Do the records show that the applicant has been in jail or prison?", "where_to_verify": "Declaration/Affidavit; Intake; Bio Call; FBI; Court dispositions, Criminal record."},
                        {"code": "4.1.H", "description": "Do the records show that the applicant has been the beneficiary of a pardon, amnesty, rehabilitation, clemency, or similar action?", "where_to_verify": "Official documents (client docs); Court record, FBI, Bio Call"},
                        {"code": "4.1.I", "description": "Do the records show that the applicant has exercised diplomatic immunity to avoid prosecution for a criminal offense in the U.S.?", "where_to_verify": "Intake; Declaration; Intake; BIOCALL, any documentation, FBI"},
                        {"code": "4.1. (Trigger)", "description": "If any of 4.1.A-4.1.I is Yes, did you verify the incident table is completed (date (*Remember to use the proper format (Mmm DD YYYY)) /place/why/outcome)?", "where_to_verify": "Part 9 incident table; dispositions/FOIA as needed"},
                    ],
                },
                {
                    "code": "4.2",
                    "name": "Prostitution / Vice / Smuggling / Drug trafficking",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.2.A", "description": "Do the records show that the applicant has engaged in prostitution or procurement of prostitution, or intends to engage?", "where_to_verify": "Intake; Bio Call; Declaration (flag trafficking nexus); Criminal record; FBI"},
                        {"code": "4.2.B", "description": "Do the records show that the applicant has engaged in unlawful commercialized vice (including illegal gambling)?", "where_to_verify": "Intake; Declaration; Criminal record, FBI"},
                        {"code": "4.2.C", "description": "Do the records show that the applicant has knowingly encouraged/induced/assisted/abetted/aided any alien to try to enter the U.S. illegally?", "where_to_verify": "Declaration; FOIA CBP; Bio Call (if needed), FBI"},
                        {"code": "4.2.D", "description": "Do the records show that the applicant has illicitly trafficked in any controlled substance, or knowingly assisted/abetted/colluded in illicit trafficking?", "where_to_verify": "Criminal record; Court disposition; FOIA; Bio Call, FBI"},
                    ],
                },
                {
                    "code": "4.3",
                    "name": "Security / Terrorism / Espionage / Political / Communist / Nazi persecution",
                    "subparts": [
                        {
                            "code": "4.3.1",
                            "name": "Acts (hijacking/hostage/assassination/firearms/WMD)",
                            "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                            "questions": [
                                {"code": "4.3.A", "description": "Do the records show that the applicant has committed/planned/prepared/participated/threatened/attempted/conspired (or gathered info/solicited funds for) hijacking or sabotage of any conveyance?", "where_to_verify": "Intake; FOIA (if any); Declaration; Bio-Call"},
                                {"code": "4.3.B", "description": "Do the records show that the applicant has committed/planned/etc. seizing or detaining and threatening to kill/injure/continue to detain to compel a third person/government?", "where_to_verify": "Intake; FOIA (if any); Declaration; Bio-Call"},
                                {"code": "4.3.C", "description": "Do the records show that the applicant has committed/planned/etc. assassination?", "where_to_verify": "Intake; FOIA (if any); Declaration; Bio-Call, FBI"},
                                {"code": "4.3.D", "description": "Do the records show that the applicant has committed/planned/etc. the use of any firearm with intent to endanger safety or cause substantial property damage?", "where_to_verify": "Intake; FOIA; Declaration; Criminal record (if any), Biocall, FBI"},
                                {"code": "4.3.E", "description": "Do the records show that the applicant has committed/planned/etc. the use of biological/chemical/nuclear/explosive/other dangerous device with intent to endanger safety or cause substantial damage?", "where_to_verify": "Intake; FOIA; Declaration, FBI, Biocall,"},
                            ],
                        },
                        {
                            "code": "4.3.2",
                            "name": "Terrorist organization association (INA 219 + other groups)",
                            "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                            "questions": [
                                {"code": "4.4.A", "description": "Do the records show that the applicant has been a member of / solicited money or members for / provided support for / attended military training by or on behalf of / been associated with an organization designated as terrorist under INA 219?", "where_to_verify": "Intake; FOIA; Declaration, FBI, Biocall,"},
                                {"code": "4.4.B", "description": "Do the records show that the applicant has been associated with any other group (2+ individuals) that engaged in hijacking/sabotage?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                                {"code": "4.3.B.1", "description": "Do the records show that the applicant has been associated with a group that engaged in seizing/detaining hostage-type conduct to compel a third party/government?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                                {"code": "4.3.B.2", "description": "Do the records show that the applicant has been associated with a group that engaged in assassination?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                                {"code": "4.3.B.4", "description": "Do the records show that the applicant has been associated with a group that engaged in use of firearms to endanger safety/cause substantial damage?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                                {"code": "4.3.B.5", "description": "Do the records show that the applicant has been associated with a group involved in soliciting money/members or providing material support to a terrorist organization?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                                {"code": "4.3.B.6", "description": "Do the records show that the applicant has been associated with a group that engaged in WMD/explosive/other dangerous device conduct to endanger safety/cause substantial damage?", "where_to_verify": "Intake; FOIA, FBI, Biocall,"},
                            ],
                        },
                        {
                            "code": "4.5",
                            "name": "Intent in the U.S. (espionage/overthrow/export violations)",
                            "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                            "questions": [
                                {"code": "4.5.A", "description": "Do the records show that the applicant intends to engage in the U.S. in espionage?", "where_to_verify": "FBI; Biocall,"},
                                {"code": "4.5.B", "description": "Do the records show that the applicant intends to engage in unlawful activity or activity to oppose/control/overthrow the U.S. government?", "where_to_verify": "Intake, FBI, Biocall,"},
                                {"code": "4.5.C", "description": "Do the records show that the applicant intends to engage in activity related to espionage/sabotage or to violate export laws involving goods/technology/sensitive info?", "where_to_verify": "Intake, FBI, Biocall,"},
                            ],
                        },
                        {
                            "code": "4.6-4.7",
                            "name": "Communist/totalitarian party + Nazi-era persecution",
                            "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                            "questions": [
                                {"code": "4.6", "description": "Do the records show that the applicant has ever been or continues to be a member of the Communist or other totalitarian party (except involuntary membership)?", "where_to_verify": "Intake; Country history; Personal history, Biocall,"},
                                {"code": "4.7", "description": "Do the records show whether, during 3/23/1933-5/8/1945, the applicant ordered/incited/assisted/participated in persecution in association with Nazi Germany (or allied org/government)?", "where_to_verify": "Country history; Personal history; Intake, Birth Certificate (Axis)"},
                            ],
                        },
                    ],
                },
                {
                    "code": "4.8-4.9",
                    "name": "Presence near harm + Immigration proceedings/removal/visa denial/voluntary departure",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.8.A", "description": "Do the records show that the applicant has been present or nearby when someone was intentionally killed, tortured, beaten, or injured?", "where_to_verify": "Intake; Personal history; Declaration; Biocall,"},
                        {"code": "4.8.B", "description": "Do the records show that the applicant has been present or nearby when someone was displaced/moved by force/compulsion/duress?", "where_to_verify": "Intake; Country history; Declaration; Biocall,"},
                        {"code": "4.8.C", "description": "Do the records show that the applicant has been present or nearby when someone was forced to engage in sexual contact/relations?", "where_to_verify": "Intake; Personal history; Declaration, Biocall,"},
                        {"code": "4.9.A", "description": "Do the records show that removal/exclusion/rescission/deportation proceedings are pending?", "where_to_verify": "EOIR portal; FOIA EOIR/ICE; Intake; Biocall,"},
                        {"code": "4.9.B", "description": "Do the records show that removal/exclusion/rescission/deportation proceedings have been initiated?", "where_to_verify": "EOIR portal; FOIA EOIR/ICE; Intake; Biocall,"},
                        {"code": "4.9.C", "description": "Do the records show that the applicant has been removed/excluded/deported from the U.S.?", "where_to_verify": "FOIA CBP/ICE/EOIR/FBI, Intake; Biocall,"},
                        {"code": "4.9.D", "description": "Do the records show that the applicant has been ordered removed/excluded/deported?", "where_to_verify": "FOIA EOIR/ICE/FBI; EOIR portal, Intake; Biocall,"},
                        {"code": "4.9.E", "description": "Do the records show that the applicant has been denied a visa or denied admission to the U.S.?", "where_to_verify": "Client docs; Declaration; FOIA (as needed), Biocall,"},
                        {"code": "4.9.F", "description": "Do the records show that the applicant was granted voluntary departure and failed to depart within the allotted time?", "where_to_verify": "FOIA EOIR; EOIR portal, Intake; Bio-call,"},
                    ],
                },
                {
                    "code": "4.10",
                    "name": "Torture/Genocide/Killing/Injury/Forced sex/Religious limits",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.10.A", "description": "Do the records show that the applicant has ordered/incited/called for/committed/assisted/participated in torture or genocide?", "where_to_verify": "Personal history; Country history; Bio Call"},
                        {"code": "4.10.B", "description": "Do the records show that the applicant has participated in killing any person?", "where_to_verify": "Personal history; Intake, FBI; Bio Call"},
                        {"code": "4.10.C", "description": "Do the records show that the applicant has participated in intentionally and severely injuring any person?", "where_to_verify": "Personal history; Intake, FBI, Bio Call"},
                        {"code": "4.10.D", "description": "Do the records show that the applicant has engaged in sexual contact/relations with someone being forced or threatened?", "where_to_verify": "Personal history; Intake, FBI, Bio Call"},
                        {"code": "4.10.E", "description": "Do the records show that the applicant has participated in limiting/denying religious beliefs?", "where_to_verify": "Country history; Bio Call Personal history, FBI"},
                    ],
                },
                {
                    "code": "4.11-4.14",
                    "name": "Military/Paramilitary/Detention/Weapons/Training",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.11.A", "description": "Do the records show that the applicant has served in/been a member of/assisted/participated in any military/paramilitary/police/self-defense/vigilante/rebel/guerrilla/militia/insurgent organization?", "where_to_verify": "Intake; Personal/Country history, FBI, Bio Call"},
                        {"code": "4.11.B", "description": "Do the records show that the applicant has served in any prison/jail/detention facility/labor camp or other situation involving detaining persons?", "where_to_verify": "Intake; Personal history, FBI, Bio Call"},
                        {"code": "4.12", "description": "Do the records show that the applicant has participated in any group where any person used a weapon against someone or threatened to?", "where_to_verify": "Intake; Personal history, FBI, Bio Call"},
                        {"code": "4.13", "description": "Do the records show that the applicant has assisted/participated in selling/providing/transporting weapons to someone they knew used them against others?", "where_to_verify": "Intake; Personal history, FBI, Bio Call"},
                        {"code": "4.14", "description": "Do the records show that the applicant has received military/paramilitary/weapons training?", "where_to_verify": "Intake; Personal history (DECLARATION BACKGROUND), FBI, Bio Call"},
                    ],
                },
                {
                    "code": "4.15-4.20",
                    "name": "Civil penalty / fraud-misrep / draft / child custody / polygamy / stowaway",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.15", "description": "Do the records show that the applicant is under a final order or civil penalty for violating INA 274C (false documentation)?", "where_to_verify": "FOIA; Prior filings; Client docs, declaration; Bio Call"},
                        {"code": "4.16", "description": "Do the records show that the applicant, by fraud or willful misrepresentation, sought to procure a visa/documentation/entry/immigration benefit?", "where_to_verify": "FOIA; Prior filings; Declaration; Work history, Intake; Bio Call"},
                        {"code": "4.17", "description": "Do the records show that the applicant left the U.S. to avoid being drafted into the U.S. Armed Forces?", "where_to_verify": "Intake; Personal history, FBI, Bio Call"},
                        {"code": "4.18", "description": "Do the records show that the applicant has withheld custody of a child with lawful claim to U.S. citizenship outside the U.S. from a U.S. citizen granted custody?", "where_to_verify": "Court records (custody); Intake, FBI, Declaration; Bio Call"},
                        {"code": "4.19", "description": "Do the records show that the applicant plans to practice polygamy in the U.S.?", "where_to_verify": "Intake; Declaration; Bio Call"},
                        {"code": "4.20", "description": "Do the records show that the applicant entered the U.S. as a stowaway?", "where_to_verify": "Declaration; FOIA CBP, Intake, Bio Call"},
                    ],
                },
                {
                    "code": "4.21",
                    "name": "Health",
                    "note": "IF ANY QUESTION IS ANSWERED YES, WE MUST VERIFY THAT WE ADD THE EXPLANATION ON THE PART 9 (ADDENDUM)",
                    "questions": [
                        {"code": "4.21.A", "description": "Do the records show that the applicant has a communicable disease of public health significance?", "where_to_verify": "Medical records, Declaration, Bio-Call. (disease: Active Tuberculosis (TB): Specifically infections TB; Infectious Syphilis; Gonorrhea; Infectious Hansen's Disease (Leprosy))"},
                        {"code": "4.21.B", "description": "Do the records show that the applicant has/had a physical or mental disorder with behavior (or history likely to recur) posing a threat to property/safety/welfare of self/others?", "where_to_verify": "Medical Evaluation, BioCall, Declaration"},
                        {"code": "4.21.C", "description": "Do the records show that the applicant is now or has been a drug abuser or drug addict?", "where_to_verify": "Medical Evaluation; Medical record, Bio Call, Declaration"},
                    ],
                },
            ],
        },
        {
            "code": "Part 5",
            "name": "Information About Your Family Members",
            "questions": [
                {"code": "5.1", "description": "Is the current spouse information complete and accurate? If not married, skip to part 5.3. NOTE: Does the file show whether the applicant has ever been married, whether in or outside the United States? Is the prior spouse information complete and accurate (names, dates of marriage, divorce, or annulment)? A marriage is void if a prior marriage was never dissolved through divorce or annulment.", "where_to_verify": "Marriage certificates, declaration"},
                {"code": "5.2", "description": "Is each child listed with complete and accurate information? If no children, skip to part 6. NOTE: Does the file show whether the applicant has children, including biological, adopted, or stepchildren?", "where_to_verify": "BioCall; Birth Certificates"},
                {"code": "5.3", "description": "Did you verify that each child is listed with full name, DOB, country of birth, and current location?", "where_to_verify": "BioCall; Birth Certificates"},
                {"code": "5.4", "description": "Did you verify children from prior relationships are included (even if no contact)?", "where_to_verify": "Declaration/Affidavit; Court Records (Custody)"},
                {"code": "5.5", "description": "Did you verify stepchildren eligibility and relationship dates (marriage date to parent)?", "where_to_verify": "Marriage certificate; Birth Certificates"},
                {"code": "5.6", "description": "Did you verify adopted children details and final adoption status?", "where_to_verify": "Adoption decrees; Court orders"},
                {"code": "5.7", "description": "Did you verify child's marital status (must be unmarried for derivatives where applicable)?", "where_to_verify": "Declaration/Affidavit; Civil records"},
                {"code": "5.8", "description": "Did you verify child's age at filing to assess derivative eligibility/age-out protection?", "where_to_verify": "Birth certificates; Filing date"},
                {"code": "5.9", "description": "Did you verify current address/location for each listed family member?", "where_to_verify": "Declaration/Affidavit; Contact Records; Google maps"},
                {"code": "5.10", "description": "Did you verify whether any family member is deceased (and properly noted)?", "where_to_verify": "Death certificates; Declaration/Affidavit"},
                {"code": "5.11", "description": "Did you verify whether the applicant is requesting derivatives now?", "where_to_verify": "I-914; Strategy Memo"},
                {"code": "5.12", "description": "If derivatives are requested, did you verify I-914A prepared for each eligible family member?", "where_to_verify": "I-914A drafts; Filing checklist"},
                {"code": "5.13", "description": "Did you verify consistency between Part 5, Declaration, I-914A (if any), and prior filings?", "where_to_verify": "Prior filings; FOIA USCIS; Case file"},
            ],
        },
        {
            "code": "Part 6",
            "name": "Applicant's Statement, Contact Information, Certification, and Signature",
            "questions": [
                {"code": "6.1", "description": "Is it correct that the applicant can read and understand English? Select Box A only if yes.", "where_to_verify": "Bio Call"},
                {"code": "6.1.A-B", "description": "If an interpreter was used, does this section match the case file? Notes: If client speaks a different language than English or Spanish, they can freely look for an interpreter; if they speak Eng or Spa, interpreter will be the CASE MANAGER assigned on the case; if an old case manager is in the application, we must correct that and put the new one.", "where_to_verify": "Bio Call"},
                {"code": "6.2", "description": "Is the preparer information correct, and does it match Part 8? Preparer will be the CASE MANAGER assigned on the case, if an old case manager is in the application, we must correct that and put the new one", "where_to_verify": "Part 6; Part 8"},
                {"code": "6.3/6.4/6.5", "description": "Is all applicant contact information complete and consistent? MUST BE CONSISTENCE FROM ALL OF THE FORM", "where_to_verify": "Intake; Bio Call; BOS"},
                {"code": "6.6", "description": "Did the applicant sign and date the form in ink?", "where_to_verify": "Original I-914"},
            ],
        },
        {
            "code": "Part 7",
            "name": "Interpreter's Contact Information, Certification, and Signature",
            "questions": [
                {"code": "7.1", "description": "Is the interpreter's full legal name listed correctly? CASE MANAGER assigned on the case; if an old case manager is in the application, we must correct that and put the new one.", "where_to_verify": "BOS"},
                {"code": "7.2", "description": "Is the interpreter's organization listed correctly? *this must be filled out if 6.1.B is checked*", "where_to_verify": "If Spanish or English: Law Offices of Manuel E. Solis. If other language: client doc. of interpretation services"},
                {"code": "7.3", "description": "Is the interpreter's mailing address correct? *If interpreter is from Law Offices of Manuel E. Solis* If not, we must filled out with the client's interpreter information", "where_to_verify": "English/Spanish P.O. Box 231704 Houston, TX 77223; Other languages: Client will provide this information."},
                {"code": "7.4/7.5/7.6", "description": "Is the interpreter's contact information complete? Daytime Phone Number; Safe daytime number; Email Address; If other interpreter is used, provide the information of them (client will provide this information)", "where_to_verify": "713-8442700; uscism@manuelsolis.com"},
                {"code": "7.7", "description": "Is the interpreter certification complete? Did the interpreter sign and date the form in ink?", "where_to_verify": "BOS (case manager assigned)"},
            ],
        },
        {
            "code": "Part 8",
            "name": "Preparer's Contact Information, Declaration, and Signature",
            "questions": [
                {"code": "8.1/8.2", "description": "Are the preparer's full name and organization listed correctly? CASE MANAGER assigned on the case; if an old case manager is in the application, we must correct that and put the new one.", "where_to_verify": "BOS"},
                {"code": "8.3", "description": "Is the preparer's mailing address correct?", "where_to_verify": "P.O. Box 231704 Houston, TX 77223"},
                {"code": "8.4/8.5/8.6", "description": "Is the preparer's contact information complete (phone numbers and email address)?", "where_to_verify": "713-8442700; uscism@manuelsolis.com"},
                {"code": "8.7", "description": "Is the preparer correctly identified as an attorney or accredited representative, and is the bar or DOJ information correct?", "where_to_verify": "CHECK BOX B \"IM NOT AN ATTORNEY\" AND does not extend beyond the preparation of this application."},
                {"code": "8.8", "description": "Did the preparer sign and date the form in ink?", "where_to_verify": "Original I-914"},
            ],
        },
        {
            "code": "Part 9",
            "name": "Additional Information",
            "questions": [
                {"code": "9.1", "description": "Does each explanation include the correct Page, Part, and Item Number?", "where_to_verify": "Part 9 entries"},
                {"code": "9.2", "description": "Are the explanations clear, specific, complete, and free of grammatical mistakes?", "where_to_verify": "Part 9; Declaration"},
                {"code": "9.3", "description": "Do the additional sheets include the applicant's name and A-Number, if any, and is each additional page dated?", "where_to_verify": "Attachments"},
            ],
        },
    ],
    "reference_sources": {
        "Internal case sources": "Bio Call (BOS); Intake (BOS); BOS (BOS); Previous Docs / CL documents of previous process (BOS)",
        "Identity & civil": "Birth Certificate / Birth Cert / Birth certificates; Passport / passports; Travel Document; IDs",
        "Immigration / history": "Form I-94 / I-94 / I94; USCIS Online Account Number (source: Bio Call); EOIR portal",
        "Trafficking / eligibility narrative": "Declaration / Affidavit",
        "Law enforcement": "LEA Report; Police Report; FBI Records / FBI",
        "Criminal / court": "Criminal record; Court disposition / court dispositions; Outcome; Official documents (Check client docs) (pardon/amnesty/clemency)",
        "FOIA (by agency, as listed)": "FOIA (generic); FOIA CBP; FOIA EOIR; FOIA EOIR/ICE; FOIA USCIS",
        "Medical": "Medical; Medical Record; Medical Evaluation",
        "Other verification sources": "Intake / Declaration; Work history; Country History; Personal history",
        "Family / derivative supporting docs": "Marriage certificate / Marriage certificates; Divorce decrees; Annulment orders; Adoption records / birth/adoption records; Adoption decrees; Court orders; Court Records (Custody); civil records; Death certificates; Contact Records",
        "Filing / packet components": "Original I-914; I-914 (entire form / Parts referenced as sources); I-914A drafts; Filing checklist; Strategy Memo; G-28 (if applicable); Prior filings; Case file; Part 9 entries; Attachments / additional sheets",
    },
}

